dist: xenial
language: python

# Existing Python versions
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install -r requirements_ci.txt

# run tests
script:
  - coverage run --source=author-rank pytest /tests

# report results
after_success:
  - coveralls
